### ISSUE TITLE
안녕하세요 ui조금 변경가능하실까요?

### ISSUE THREAD

**Issue by lssaass** [kkk477/Hellfire-Delay-Viewer#1]
창모드 일때는 보기 쉬웠는데
전체모드할떄는 보기가 불편해서요 ㅠ
바람의나라 실행중에도 위에 올려둘수있게 
반투명으로 바람실행창위에 올려둘수있게 해주실수있을까요 ㅠ?

**Comment by kkk477** [comment]
0.3.0 preview 버전을 추가했습니다.
